/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                            uptime: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: {
            parameters: {
                query?: {
                    /** @description Max acceptable ledger lag */
                    maxLag?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            checks: {
                                db: boolean;
                                rpc: boolean;
                                indexerCaughtUp: boolean;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            checks: {
                                db: boolean;
                                rpc: boolean;
                                indexerCaughtUp: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexer status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                            lastIndexedLedger: number | null;
                            latestLedger: number;
                            lagLedgers: number;
                            /** Format: date-time */
                            startedAt: string;
                            uptimeSeconds: number;
                            totalIndexed: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/incoming/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incoming transfers */
        get: {
            parameters: {
                query?: {
                    /** @description Token contract ID to filter by */
                    contractId?: string | null;
                    token?: string;
                    fromLedger?: number | null;
                    toLedger?: number | null;
                    /** @description Inclusive lower bound on ledgerClosedAt */
                    fromDate?: string | null;
                    /** @description Inclusive upper bound on ledgerClosedAt */
                    toDate?: string | null;
                    /** @description Comma-separated list of event types */
                    eventType?: string[] | null;
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                    /** @description Opaque pagination cursor */
                    cursor?: string | null;
                    /** @description OData filter expression */
                    $filter?: string | null;
                    /** @description Comma-separated field list */
                    $select?: string[] | null;
                };
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            limit: number;
                            offset: number;
                            nextCursor?: string | null;
                            transfers: {
                                id: number;
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                /** @enum {string} */
                                eventType: "transfer" | "mint" | "burn" | "clawback";
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                fromAddress: string | null;
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                toAddress: string | null;
                                amount: string;
                                displayAmount: string;
                                ledger: number;
                                /** Format: date-time */
                                ledgerClosedAt: string;
                                txHash: string;
                                eventId: string;
                                /** @enum {string} */
                                direction?: "incoming" | "outgoing";
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/outgoing/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outgoing transfers */
        get: {
            parameters: {
                query?: {
                    /** @description Token contract ID to filter by */
                    contractId?: string | null;
                    token?: string;
                    fromLedger?: number | null;
                    toLedger?: number | null;
                    /** @description Inclusive lower bound on ledgerClosedAt */
                    fromDate?: string | null;
                    /** @description Inclusive upper bound on ledgerClosedAt */
                    toDate?: string | null;
                    /** @description Comma-separated list of event types */
                    eventType?: string[] | null;
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                    /** @description Opaque pagination cursor */
                    cursor?: string | null;
                    /** @description OData filter expression */
                    $filter?: string | null;
                    /** @description Comma-separated field list */
                    $select?: string[] | null;
                };
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            limit: number;
                            offset: number;
                            nextCursor?: string | null;
                            transfers: {
                                id: number;
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                /** @enum {string} */
                                eventType: "transfer" | "mint" | "burn" | "clawback";
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                fromAddress: string | null;
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                toAddress: string | null;
                                amount: string;
                                displayAmount: string;
                                ledger: number;
                                /** Format: date-time */
                                ledgerClosedAt: string;
                                txHash: string;
                                eventId: string;
                                /** @enum {string} */
                                direction?: "incoming" | "outgoing";
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/address/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All transfers for address */
        get: {
            parameters: {
                query?: {
                    /** @description Token contract ID to filter by */
                    contractId?: string | null;
                    token?: string;
                    fromLedger?: number | null;
                    toLedger?: number | null;
                    /** @description Inclusive lower bound on ledgerClosedAt */
                    fromDate?: string | null;
                    /** @description Inclusive upper bound on ledgerClosedAt */
                    toDate?: string | null;
                    /** @description Comma-separated list of event types */
                    eventType?: string[] | null;
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                    /** @description Opaque pagination cursor */
                    cursor?: string | null;
                    /** @description OData filter expression */
                    $filter?: string | null;
                    /** @description Comma-separated field list */
                    $select?: string[] | null;
                };
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            limit: number;
                            offset: number;
                            nextCursor?: string | null;
                            transfers: {
                                id: number;
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                /** @enum {string} */
                                eventType: "transfer" | "mint" | "burn" | "clawback";
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                fromAddress: string | null;
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                toAddress: string | null;
                                amount: string;
                                displayAmount: string;
                                ledger: number;
                                /** Format: date-time */
                                ledgerClosedAt: string;
                                txHash: string;
                                eventId: string;
                                /** @enum {string} */
                                direction?: "incoming" | "outgoing";
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/address/{address}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export transfers to CSV */
        get: {
            parameters: {
                query?: {
                    /** @description Token contract ID to filter by */
                    contractId?: string | null;
                    token?: string;
                    fromLedger?: number | null;
                    toLedger?: number | null;
                    /** @description Inclusive lower bound on ledgerClosedAt */
                    fromDate?: string | null;
                    /** @description Inclusive upper bound on ledgerClosedAt */
                    toDate?: string | null;
                    /** @description Comma-separated list of event types */
                    eventType?: string[] | null;
                };
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV export */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers/tx/{txHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transfers by transaction */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Transaction hash */
                    txHash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            transfers: {
                                id: number;
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                /** @enum {string} */
                                eventType: "transfer" | "mint" | "burn" | "clawback";
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                fromAddress: string | null;
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                toAddress: string | null;
                                amount: string;
                                displayAmount: string;
                                ledger: number;
                                /** Format: date-time */
                                ledgerClosedAt: string;
                                txHash: string;
                                eventId: string;
                                /** @enum {string} */
                                direction?: "incoming" | "outgoing";
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token summary */
        get: {
            parameters: {
                query?: {
                    /** @description Token contract ID to filter by */
                    contractId?: string | null;
                    /** @description Inclusive lower bound on ledgerClosedAt */
                    fromDate?: string | null;
                    /** @description Inclusive upper bound on ledgerClosedAt */
                    toDate?: string | null;
                };
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                            address: string;
                            window: {
                                /**
                                 * Format: date-time
                                 * @example 2025-01-01T00:00:00Z
                                 */
                                fromDate: string | null;
                                /**
                                 * Format: date-time
                                 * @example 2025-01-01T00:00:00Z
                                 */
                                toDate: string | null;
                            };
                            tokens: {
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                totalReceived: string;
                                totalSent: string;
                                netFlow: string;
                                displayTotalReceived: string;
                                displayTotalSent: string;
                                displayNetFlow: string;
                                txCount: number;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{address}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token summary */
        get: {
            parameters: {
                query?: {
                    /** @description Token contract ID to filter by */
                    contractId?: string | null;
                    /** @description Inclusive lower bound on ledgerClosedAt */
                    fromDate?: string | null;
                    /** @description Inclusive upper bound on ledgerClosedAt */
                    toDate?: string | null;
                };
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                            address: string;
                            window: {
                                /**
                                 * Format: date-time
                                 * @example 2025-01-01T00:00:00Z
                                 */
                                fromDate: string | null;
                                /**
                                 * Format: date-time
                                 * @example 2025-01-01T00:00:00Z
                                 */
                                toDate: string | null;
                            };
                            tokens: {
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                totalReceived: string;
                                totalSent: string;
                                netFlow: string;
                                displayTotalReceived: string;
                                displayTotalSent: string;
                                displayNetFlow: string;
                                txCount: number;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{address}/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account transfers */
        get: {
            parameters: {
                query?: {
                    /** @description Token contract ID to filter by */
                    contractId?: string | null;
                    token?: string;
                    fromLedger?: number | null;
                    toLedger?: number | null;
                    /** @description Inclusive lower bound on ledgerClosedAt */
                    fromDate?: string | null;
                    /** @description Inclusive upper bound on ledgerClosedAt */
                    toDate?: string | null;
                    /** @description Comma-separated list of event types */
                    eventType?: string[] | null;
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                    /** @description Opaque pagination cursor */
                    cursor?: string | null;
                    /** @description OData filter expression */
                    $filter?: string | null;
                    /** @description Comma-separated field list */
                    $select?: string[] | null;
                };
                header?: never;
                path: {
                    address: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            limit: number;
                            offset: number;
                            nextCursor?: string | null;
                            transfers: {
                                id: number;
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                /** @enum {string} */
                                eventType: "transfer" | "mint" | "burn" | "clawback";
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                fromAddress: string | null;
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                toAddress: string | null;
                                amount: string;
                                displayAmount: string;
                                ledger: number;
                                /** Format: date-time */
                                ledgerClosedAt: string;
                                txHash: string;
                                eventId: string;
                                /** @enum {string} */
                                direction?: "incoming" | "outgoing";
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook subscriptions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            subscriptions: {
                                id: number;
                                url: string;
                                filter: {
                                    contract?: string;
                                    from?: string;
                                    to?: string;
                                    min_amount?: string;
                                } | null;
                                active: boolean;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a webhook subscription */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                        secret: string;
                        filter?: {
                            contract?: string;
                            from?: string;
                            to?: string;
                            min_amount?: string;
                        } | null;
                        active?: boolean;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            url: string;
                            filter: {
                                contract?: string;
                                from?: string;
                                to?: string;
                                min_amount?: string;
                            } | null;
                            active: boolean;
                            /** Format: date-time */
                            createdAt: string;
                            signatureVerification: {
                                /** @enum {string} */
                                header: "X-Wraith-Signature";
                                /** @enum {string} */
                                algorithm: "sha256";
                                format: string;
                                body: string;
                                example: string;
                                safeCompare: string;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook subscription */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Webhook delivery log */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "success" | "failed";
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                };
                header?: never;
                path: {
                    id: number | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            limit: number;
                            offset: number;
                            deliveries: {
                                id: number;
                                eventId: string;
                                status: string;
                                attempts: number;
                                lastStatusCode: number | null;
                                lastError: string | null;
                                /** Format: date-time */
                                nextRetryAt: string | null;
                                /** Format: date-time */
                                deliveredAt: string | null;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/host-fn/{contractId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Host function logs */
        get: {
            parameters: {
                query?: {
                    /** @description Host function name to filter by */
                    functionName?: string | null;
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                };
                header?: never;
                path: {
                    contractId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                            contractId: string;
                            total: number;
                            limit: number;
                            offset: number;
                            logs: {
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                functionName: string;
                                args?: unknown;
                                result?: unknown;
                                gasUsed: string | null;
                                ledger: number;
                                /** Format: date-time */
                                ledgerClosedAt: string;
                                txHash: string;
                                eventId: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfts/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NFT transfers */
        get: {
            parameters: {
                query?: {
                    /** @description NFT contract ID to filter by */
                    contract?: string | null;
                    /** @description NFT token identifier */
                    token_id?: string | null;
                    /** @description Filter by sender or recipient address */
                    address?: string | null;
                    fromLedger?: number | null;
                    toLedger?: number | null;
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                    /** @description Opaque pagination cursor */
                    cursor?: string | null;
                    /** @description OData filter expression */
                    $filter?: string | null;
                    /** @description Comma-separated field list */
                    $select?: string[] | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            limit: number;
                            offset: number;
                            nextCursor?: string | null;
                            transfers: {
                                id: number;
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                tokenId: string;
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                fromAddress: string | null;
                                /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                                toAddress: string | null;
                                ledger: number;
                                /** Format: date-time */
                                ledgerClosedAt: string;
                                txHash: string;
                                eventId: string;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfts/owners/{contract}/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NFT owner lookup */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    contract: string;
                    token_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                            contract: string;
                            token_id: string;
                            /** @example GABCDEFGHIJKLMNOPQRSTUVWXYZ */
                            owner: string;
                            metadata: {
                                name: string | null;
                                tokenUri: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Popular assets */
        get: {
            parameters: {
                query?: {
                    window?: "1h" | "24h" | "7d";
                    by?: "transfers" | "volume";
                    /** @description Page size */
                    limit?: number | null;
                    /** @description Pagination offset */
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            window: "1h" | "24h" | "7d";
                            /** @enum {string} */
                            by: "transfers" | "volume";
                            limit: number;
                            offset: number;
                            total: number;
                            assets: {
                                /** @example CB64D3G7SM2RTH6ISYIG4P2IYYD6J2OFR6B */
                                contractId: string;
                                transferCount: number;
                                volume: string;
                                displayVolume: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fuzzy search across accounts, assets, and contracts */
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            query: string;
                            count: number;
                            results: {
                                /** @enum {string} */
                                type: "account" | "asset" | "contract";
                                value: string;
                                isSac?: boolean;
                                lastActivityAt?: string;
                            }[];
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
